swagger: '2.0'
info:
  title: Melown cloud
  version: '0.1.2'
  description: 'Melown cloud API.'
schemes:
  - https
host: www.test.mlwn.se
basePath: /cloud/backend/api
consumes:
  - 'application/json'
produces:
  - 'application/json'
securityDefinitions:
  melownAccounts:
    description: 'Melown Accounts'
    type: oauth2
    flow: implicit
    authorizationUrl: 'https://www.test.mlwn.se/accounts/auth/init'
    scopes:
      MARIO_API: 'Melown-cloud-API'
security:
  - melownAccounts: [MARIO_API]

#===============================================================================
# tags
tags:
  - name: Account
    description: Account-related data.

  - name: Account-User
    description: User in an account.

  - name: Dataset
    description: Datasets.

  - name: Invitation
    description: Invitations in an account.

  - name: 'Map-Application'
    description: Application for a certain map.

  - name: 'Map-Configuration'
    description: Maps.

  - name: 'Reference frame'
    description: List of reference frames.

  - name: 'Resources'
    description: Resources.

  - name: 'Resource category'
    description: List of resource categories.

  - name: 'Analytics'
    description: Statistics about recent updates.

  - name: 'User profile'
    description: "The current user's profile."


#===============================================================================
# Paths
paths:
  #-----------------------------------------------------------------------------
  # Account
  # get
  '/account/{accountId}':
    $ref: 'account/index.yaml#/accountGet'

  # Account-user: add, update, delete
  '/account/{accountId}/user/{userId}':
    $ref: 'account/index.yaml#/accountUser'

  # Account-invitation: resend
  '/account/{accountId}/invitation/{invitationId}/resend':
    $ref: 'account/index.yaml#/accountInvitationResend'

  # Create
  '/account/{accountId}/invitation':
    $ref: 'account/index.yaml#/accountInvitationCreate'

  # Delete
  '/account/{accountId}/invitation/{invitationId}':
    $ref: 'account/index.yaml#/accountInvitationDelete'

  # Get datasets
  '/account/{accountId}/dataset':
    $ref: 'account/index.yaml#/accountDatasetGet'

  #-----------------------------------------------------------------------------
  # Analytics
  # get updated datasets
  '/analytics/updateddatasets':
    $ref: 'analytics/index.yaml#/updateddatasets'

  # get updated maps
  '/analytics/updatedmaps':
    $ref: 'analytics/index.yaml#/updatedmaps'

  #-----------------------------------------------------------------------------
  # Application
  # list

  # get
  '/application/{appIdentifier}':
    $ref: 'application/index.yaml#/getApplication'

  #-----------------------------------------------------------------------------
  # Dataset
  # get, put, delete
  '/dataset/{datasetId}':
    $ref: 'dataset/index.yaml#/getPutDelete'

  # get duplicate
  '/dataset/{datasetId}/duplicate':
    $ref: 'dataset/index.yaml#/duplicate'

  # get cancel
  '/dataset/{datasetId}/cancel':
    $ref: 'dataset/index.yaml#/cancel'

  # get references
  '/dataset/{datasetId}/references':
    $ref: 'dataset/index.yaml#/references'

  # post export
  '/dataset/{datasetId}/export':
    $ref: 'dataset/index.yaml#/export'

  #-----------------------------------------------------------------------------
  # Map-config
  # list
  '/map_config':
    $ref: 'map-config/index.yaml#/listMapConfigs'

  # get, put, delete
  '/map_config/{mapConfigId}':
    $ref: 'map-config/index.yaml#/getPutDelete'

  # glues - get status
  '/map_config/{mapConfigId}/glue/status':
    $ref: 'map-config/index.yaml#/glueStatus'

  # glues - plan
  '/map_config/{mapConfigId}/glue/plan':
    $ref: 'map-config/index.yaml#/gluePlan'

  # glues - progress
  '/map_config/{mapConfigId}/glue/progress':
    $ref: 'map-config/index.yaml#/glueProgress'

  #-----------------------------------------------------------------------------
  # reference frame
  # get
  '/reference_frame':
    $ref: 'reference-frame/index.yaml#/getReferenceFrame'

  #-----------------------------------------------------------------------------
  # resource category
  # get
  '/resource_category':
    $ref: 'resource-category/index.yaml#/getResourceCategory'

  #-----------------------------------------------------------------------------
  # resource
  # list
  '/resource':
    $ref: 'resource/index.yaml#/listResources'

  # get, put, delete
  '/resource/{resourceId}':
    $ref: 'resource/index.yaml#/getPutDelete'

  # get references
  '/resource/{resourceId}/references':
    $ref: 'resource/index.yaml#/references'

  #-----------------------------------------------------------------------------
  # profile
  # get, put
  '/me':
    $ref: 'profile/index.yaml#/getPutProfile'
