#===============================================================================
# Parameters

accessToken:
  in: query
  name: access_token
  description: "User's access token. Can be used instead of an Authorization-header."
  required: false
  type: string

appId:
  in: query
  name: app_id
  description: 'Current application-ID.'
  required: true
  type: string

appIdentifier:
  in: path
  name: appIdentifier
  description: 'Application-ID for a certain map.'
  required: true
  type: string

accountId:
  in: path
  name: accountId
  description: 'ID of the account.'
  required: true
  type: integer

datasetId:
  in: path
  name: datasetId
  description: 'ID of a dataset.'
  required: true
  type: integer

invitationId:
  in: path
  name: invitationId
  description: 'ID of the account.'
  required: true
  type: integer

userId:
  in: path
  name: userId
  description: 'ID of the user.'
  required: true
  type: integer

mapConfigId:
  in: path
  name: mapConfigId
  description: 'ID of a map.'
  required: true
  type: integer

resourceId:
  in: path
  name: resourceId
  description: 'ID of a resource.'
  required: true
  type: integer

page:
  in: query
  name: page
  description: 'Current result-page.'
  required: false
  type: integer
  default: 1

userData:
  in: body
  name: userData
  description: 'Data for user.'
  required: true
  schema:
    type: object
    properties:
      role:
        type: string
        enum: [user, admin]
        description: Role of the user in account.

datasetExport:
  in: body
  name: datasetInfo
  description: 'Export-settings for dataset.'
  required: true
  schema:
    type: object
    required: [name, caption, description, zshift]
    properties:
      name:
        type: string
        description: Name of the resource to export.
      caption:
        type: string
        description: 'Additional short description, used in tooltips.'
      description:
        type: string
        description: Additional description.
      zshift:
        type: string
        description: If the dataset needs z-shifting, this is the value (in m).

newMapConfig:
  in: body
  name: newMapConfig
  description: 'Data for new map.'
  required: true
  schema:
    type: object
    required: [name, owner_account_id, reference_frame_id]
    properties:
      name:
        type: string
        description: 'Name for the new map.'
      owner_account_id:
        type: integer
        description: 'Account under which the map will be created.'
      reference_frame_id:
        type: string
        description: 'Reference frame for the map.'
      title:
        type: string
        description: 'Title of the map.'
      description:
        type: string
        description: 'Description for the map.'
      rotation:
        type: number
        description: 'Initial rotation.'
      position:
        type: string
        description: 'Initial position.'
      flag_example:
        type: boolean
        description: 'If true, this map will become a publically available example.'

updateMapConfig:
  in: body
  name: updateMapConfig
  description: 'Data for updating a map.'
  required: true
  schema:
    type: object
    properties:
      name:
        type: string
        description: 'Name of the map.'
      title:
        type: string
        description: 'Title of the map.'
      description:
        type: string
        description: 'Description for the map.'
      rotation:
        type: number
        description: 'New rotation.'
      position:
        type: string
        description: 'New position.'
      flag_example:
        type: boolean
        description: 'If true, this map will become a publically available example.
          This can be changed only by superadmins.'
      resources:
        type: array
        description: 'Complete list of resource-IDs for this map. When given, existing
          resources will be replaced.'
        items:
          type: integer
          description: Resouce-ID.

newInvitation:
  type: object
  required: [email]
  properties:
    email:
      type: string
      description: Receiver-email.
    count:
      type: integer
      description: 'How often this invitation can be accepted (optional,
        defaults to 0 - unlimited).'
    time_valid_until:
      type: string
      format: date-time
      description: 'Until when this invitation can be accepted (optional,
        defaults to null - forever).'

newDataset:
  type: object
  required: [name, type]
  properties:
    name:
      type: string
      description: Name given by the uploader.
    type:
      type: string
      description: Type of dataset.
    files:
      type: array
      description: List of files that form that dataset.
      items:
        type: object
        properties:
          byte_size:
            type: number
            description: Size of the file in bytes.
          crc:
            type: string
            description: Not used, always empty.
          path_component:
            type: string
            description: Basename (without path) of the file.

updateResource:
  in: body
  name: updateResource
  description: 'Data for updating a resource.'
  required: true
  schema:
    type: object
    properties:
      name:
        type: string
        description: 'Name of the map.'
      caption:
        type: string
        description: 'Title of the map.'
      description:
        type: string
        description: 'Description for the map.'
      position:
        type: string
        description: 'Default-position for the map.'

