swagger: '2.0'
info:
  title: Mario Console
  version: '0.1.1'
  description: 'Mario console-API.'
schemes:
  - https
host: www.melown.com
basePath: /cloud/backend/api
consumes:
  - 'application/json'
produces:
  - 'application/json'

#===============================================================================
# tags
tags:
  - name: Account
    description: Account-related data.

  - name: Invitation
    description: Invitations in an account.

  - name: Account-User
    description: User in an account.

  - name: Dataset
    description: Datasets.

  - name: 'Updated datasets'
    description: Recently updated datasets.

  - name: 'Updated maps'
    description: Recently updated maps.

  - name: 'Map-Application'
    description: Application for a certain map.

  - name: 'Map-Configuration'
    description: Configuration for a certain map.

  - name: 'Reference frame'
    description: List of reference frames.

  - name: 'Resource category'
    description: List of resource categories.

  - name: 'User profile'
    description: "The current user's profile."


#===============================================================================
# Paths
paths:
  #-----------------------------------------------------------------------------
  # Account
  # get
  '/account/{accountId}':
    $ref: 'account/index.yaml#/accountGet'

  # Account-user: add, update, delete
  '/account/{accountId}/user/{userId}':
    $ref: 'account/index.yaml#/accountUser'

  # Account-invitation: resend
  '/account/{accountId}/invitation/{invitationId}/resend':
    $ref: 'account/index.yaml#/accountInvitationResend'

  # Create
  '/account/{accountId}/invitation':
    $ref: 'account/index.yaml#/accountInvitationCreate'

  # Delete
  '/account/{accountId}/invitation/{invitationId}':
    $ref: 'account/index.yaml#/accountInvitationDelete'

  # Get datasets
  '/account/{accountId}/dataset':
    $ref: 'account/index.yaml#/accountDatasetGet'

  #-----------------------------------------------------------------------------
  # Analytics
  # get updated datasets
  '/analytics/updateddatasets':
    $ref: 'analytics/index.yaml#/updateddatasets'

  # get updated maps
  '/analytics/updatedmaps':
    $ref: 'analytics/index.yaml#/updatedmaps'

  #-----------------------------------------------------------------------------
  # Application
  # get
  '/application/{appIdentifyier}':
    $ref: 'application/index.yaml#/getApplication'

  #-----------------------------------------------------------------------------
  # Dataset
  # get, put, delete
  '/dataset/{datasetId}':
    $ref: 'dataset/index.yaml#/getPutDelete'

  # get duplicate
  '/dataset/{datasetId}/duplicate':
    $ref: 'dataset/index.yaml#/duplicate'

  # get cancel
  '/dataset/{datasetId}/cancel':
    $ref: 'dataset/index.yaml#/cancel'

  # get references
  '/dataset/{datasetId}/references':
    $ref: 'dataset/index.yaml#/references'

  # post export
  '/dataset/{datasetId}/export':
    $ref: 'dataset/index.yaml#/export'

  #-----------------------------------------------------------------------------
  # Map-config
  '/map_config':
    $ref: 'map-config/index.yaml#/listMapConfigs'

  #-----------------------------------------------------------------------------
  # reference frame
  # get
  '/reference_frame':
    $ref: 'reference-frame/index.yaml#/getReferenceFrame'

  #-----------------------------------------------------------------------------
  # resource category
  # get
  '/resource_category':
    $ref: 'resource-category/index.yaml#/getResourceCategory'

  #-----------------------------------------------------------------------------
  # resource

  #-----------------------------------------------------------------------------
  # profile
  # get, put
  '/me':
    $ref: 'profile/index.yaml#/getPutProfile'
